INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(1,'','',1);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(2,'','',1);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(3,'','',1);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(4,'','',1);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(5,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(6,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(7,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(8,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(9,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(10,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(11,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(12,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(13,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(14,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(15,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(16,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(17,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(18,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(19,'','',1)
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(20,'','',1)




