INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(1,'Ferrari',16);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(2,'Red Bull Racing RBPT',4);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(3,'Mercedes',8);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(4,'McLaren Mercedes',8);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(5,'Alfa Romeo Ferrari',0);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(6,'Alpine Renault',0);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(7,'AlphaTauri RBPT',0);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(8,'Haas Ferrari',0);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(9,'Aston Martin Aramco Mercedes',0);
INSERT INTO CONSTRUCTOR (ID, TEAM, TITLES) VALUES(10,'Williams Mercedes',9);
INSERT INTO CONSTRUCTOR (ID,TEAM,TITLES) VALUES(11,'Toyota WRC',5);
INSERT INTO CONSTRUCTOR (ID,TEAM,TITLES) VALUES(11,'Hyundai WRC',2);
INSERT INTO CONSTRUCTOR (ID,TEAM,TITLES) VALUES(11,'Ford WRC',4);
INSERT INTO CONSTRUCTOR (ID,TEAM,TITLES) VALUES(11,'Citroen WRC',8);


INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(1,'F1','Bahrain','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(2,'F1','Saudi Arabia','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(3,'F1','Australia','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(4,'F1','Italy','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(5,'F1','United States','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(6,'F1','Spain','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(7,'F1','Monaco','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(8,'F1','Azerbaijan','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(9,'F1','Canada','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(10,'F1','Great Britain','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(11,'F1','Austria','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(12,'F1','France','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(13,'F1','Hungary','');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(14,'Rally','Great Britain','Wales Rally GB');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(15,'Rally','France','Tour de Corse');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(16,'Rally','Portugal','Portugal Rally');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(17,'Rally','Finland','Rally Finland');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(18,'Rally','Italy','Rally di Sanremo');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(19,'Rally','Kenya','Safari Rally');
INSERT INTO Category(ID, SERIES, COUNTRY, CIRCUIT) VALUES(20,'Rally','Monaco','Monte Carlo Rally');


INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(1,'Charles','Leclerc',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(2,'Carlos','Sainz',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(3,'Max','Verstappen',1);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(4,'Sergio','Perez',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(5,'Lewis','Hamilton',7);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(6,'George','Russel',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(7,'Lando','Norris',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(8,'Daniel','Ricciardo',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(9,'Zhou','Guanyu',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(10,'Valtteri','Bottas',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(11,'Fernando','Alonso',2);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(12,'Esteban','Ocon',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(13,'Yuki','Tsunoda',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(14,'Pierre','Gasly',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(15,'Mick','Schumacher',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(16,'Kevin','Magnussen',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(17,'Sebastian','Vettel',4);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(18,'Lance','Stroll',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(19,'Alex','Albon',0);
INSERT INTO DRIVER (ID, FIRST_NAME, LAST_NAME,TITLES) VALUES(20,'Nicholas','Latifi',0);



}
